// frontend/src/app/dashboard/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useAuth } from '@/contexts/AuthContext'
import Navigation from '@/components/Navigation'
import { useRouter } from 'next/navigation'

interface DashboardStats {
  total_projects: number
  active_projects: number
  completed_projects: number
  total_paint_bundles: number
  recent_projects: Array<{
    id: number
    name: string
    location?: string
    created_at: string
  }>
}

export default function Dashboard() {
  const [stats, setStats] = useState<DashboardStats | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const { user, token } = useAuth()
  const router = useRouter()

  useEffect(() => {
    if (!user) {
      router.push('/login')
      return
    }
    fetchDashboardData()
  }, [user, router])

  const fetchDashboardData = async () => {
    if (!token) return

    try {
      setLoading(true)
      const response = await fetch('/api/dashboard', {
        headers: {
          'Authorization': `Bearer ${token}`,
        },
      })
      
      if (!response.ok) {
        // If dashboard API doesn't exist, create mock data
        if (response.status === 404) {
          setStats({
            total_projects: 0,
            active_projects: 0,
            completed_projects: 0,
            total_paint_bundles: 0,
            recent_projects: []
          })
          return
        }
        throw new Error('Failed to fetch dashboard data')
      }
      
      const data = await response.json()
      setStats(data)
    } catch (err) {
      console.error('Dashboard error:', err)
      // Create mock data for now
      setStats({
        total_projects: 0,
        active_projects: 0,
        completed_projects: 0,
        total_paint_bundles: 0,
        recent_projects: []
      })
    } finally {
      setLoading(false)
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50">
        <Navigation />
        <div className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
          <div className="text-center">Loading dashboard...</div>
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gray-50">
        <Navigation />
        <div className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
          <div className="text-red-600 text-center">Error: {error}</div>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <Navigation />
      
      <div className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900">
            Welcome back, {user?.name}!
          </h1>
          <p className="mt-2 text-gray-600">
            Here's an overview of your wall planning projects
          </p>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          <div className="bg-white overflow-hidden shadow rounded-lg">
            <div className="p-5">
              <div className="flex items-center">
                <div className="flex-shrink-0">
                  <div className="w-8 h-8 bg-blue-500 rounded-full flex items-center justify-center">
                    <span className="text-white text-sm font-medium">P</span>
                  </div>
                </div>
                <div className="ml-5 w-0 flex-1">
                  <dl>
                    <dt className="text-sm font-medium text-gray-500 truncate">
                      Total Projects
                    </dt>
                    <dd className="text-lg font-medium text-gray-900">
                      {stats?.total_projects || 0}
                    </dd>
                  </dl>
                </div>
              </div>
            </div>
          </div>

          <div className="bg-white overflow-hidden shadow rounded-lg">
            <div className="p-5">
              <div className="flex items-center">
                <div className="flex-shrink-0">
                  <div className="w-8 h-8 bg-green-500 rounded-full flex items-center justify-center">
                    <span className="text-white text-sm font-medium">A</span>
                  </div>
                </div>
                <div className="ml-5 w-0 flex-1">
                  <dl>
                    <dt className="text-sm font-medium text-gray-500 truncate">
                      Active Projects
                    </dt>
                    <dd className="text-lg font-medium text-gray-900">
                      {stats?.active_projects || 0}
                    </dd>
                  </dl>
                </div>
              </div>
            </div>
          </div>

          <div className="bg-white overflow-hidden shadow rounded-lg">
            <div className="p-5">
              <div className="flex items-center">
                <div className="flex-shrink-0">
                  <div className="w-8 h-8 bg-purple-500 rounded-full flex items-center justify-center">
                    <span className="text-white text-sm font-medium">C</span>
                  </div>
                </div>
                <div className="ml-5 w-0 flex-1">
                  <dl>
                    <dt className="text-sm font-medium text-gray-500 truncate">
                      Completed Projects
                    </dt>
                    <dd className="text-lg font-medium text-gray-900">
                      {stats?.completed_projects || 0}
                    </dd>
                  </dl>
                </div>
              </div>
            </div>
          </div>

          <div className="bg-white overflow-hidden shadow rounded-lg">
            <div className="p-5">
              <div className="flex items-center">
                <div className="flex-shrink-0">
                  <div className="w-8 h-8 bg-orange-500 rounded-full flex items-center justify-center">
                    <span className="text-white text-sm font-medium">B</span>
                  </div>
                </div>
                <div className="ml-5 w-0 flex-1">
                  <dl>
                    <dt className="text-sm font-medium text-gray-500 truncate">
                      Paint Bundles
                    </dt>
                    <dd className="text-lg font-medium text-gray-900">
                      {stats?.total_paint_bundles || 0}
                    </dd>
                  </dl>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Quick Actions */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
          <div className="bg-white shadow rounded-lg p-6">
            <h2 className="text-lg font-medium text-gray-900 mb-4">Quick Actions</h2>
            <div className="space-y-3">
              <button
                onClick={() => router.push('/projects')}
                className="w-full text-left px-4 py-3 border border-gray-200 rounded-md hover:bg-gray-50 flex items-center"
              >
                <div className="w-8 h-8 bg-blue-100 rounded-full flex items-center justify-center mr-3">
                  <span className="text-blue-600 text-sm">+</span>
                </div>
                <div>
                  <div className="font-medium text-gray-900">Create New Project</div>
                  <div className="text-sm text-gray-500">Start planning a new wall project</div>
                </div>
              </button>
              
              <button
                onClick={() => router.push('/paints')}
                className="w-full text-left px-4 py-3 border border-gray-200 rounded-md hover:bg-gray-50 flex items-center"
              >
                <div className="w-8 h-8 bg-green-100 rounded-full flex items-center justify-center mr-3">
                  <span className="text-green-600 text-sm">🎨</span>
                </div>
                <div>
                  <div className="font-medium text-gray-900">Browse Paint Catalog</div>
                  <div className="text-sm text-gray-500">Explore available paint colors</div>
                </div>
              </button>
            </div>
          </div>

          <div className="bg-white shadow rounded-lg p-6">
            <h2 className="text-lg font-medium text-gray-900 mb-4">Recent Projects</h2>
            {stats?.recent_projects && stats.recent_projects.length > 0 ? (
              <div className="space-y-3">
                {stats.recent_projects.slice(0, 3).map((project) => (
                  <div key={project.id} className="flex items-center py-2">
                    <div className="w-2 h-2 bg-blue-400 rounded-full mr-3"></div>
                    <div className="flex-1 min-w-0">
                      <div className="font-medium text-gray-900 truncate">
                        {project.name}
                      </div>
                      <div className="text-sm text-gray-500">
                        {project.location && `${project.location} • `}
                        {new Date(project.created_at).toLocaleDateString()}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="text-center py-6">
                <p className="text-gray-500">No projects yet</p>
                <button
                  onClick={() => router.push('/projects')}
                  className="mt-2 text-blue-600 hover:text-blue-700 text-sm font-medium"
                >
                  Create your first project
                </button>
              </div>
            )}
          </div>
        </div>

        {/* Getting Started */}
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
          <div className="flex items-start">
            <div className="flex-shrink-0">
              <div className="w-10 h-10 bg-blue-500 rounded-full flex items-center justify-center">
                <span className="text-white text-sm">💡</span>
              </div>
            </div>
            <div className="ml-4">
              <h3 className="text-lg font-medium text-blue-900">Getting Started</h3>
              <p className="mt-1 text-blue-700">
                Welcome to your wall planning dashboard! Start by creating a new project, 
                then explore our paint catalog to find the perfect colors for your space.
              </p>
              <div className="mt-4 flex space-x-4">
                <button
                  onClick={() => router.push('/projects')}
                  className="bg-blue-600 text-white px-4 py-2 rounded-md text-sm font-medium hover:bg-blue-700"
                >
                  Create Project
                </button>
                <button
                  onClick={() => router.push('/paints')}
                  className="bg-white text-blue-600 px-4 py-2 rounded-md text-sm font-medium border border-blue-300 hover:bg-blue-50"
                >
                  Browse Catalog
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// resources/js/Pages/Dashboard.vue
<template>
  <AppLayout>
    <template #header>
      <div class="flex items-center">
        <h2 class="text-2xl font-bold text-gray-900">
          Dashboard
        </h2>
        <div class="ml-3 text-sm text-gray-500">
          Welcome back, {{ userName || 'User' }}!
        </div>
      </div>
    </template>

    <div class="py-12">
      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <!-- Welcome Message -->
        <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg mb-6">
          <div class="p-6 text-gray-900">
            <h3 class="text-lg font-semibold mb-2">
              Welcome back, {{ userName }}!
            </h3>
            <p class="text-gray-600">
              Ready to plan your next wall project? Here's what you can do:
            </p>
          </div>
        </div>

        <!-- Quick Actions Grid -->
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-8">
          <!-- Browse Paint Catalog -->
          <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg hover:shadow-md transition-shadow">
            <div class="p-6">
              <div class="flex items-center">
                <div class="flex-shrink-0">
                  <div class="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center">
                    <svg class="w-6 h-6 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 21a4 4 0 01-8 0 4 4 0 018 0zM7 21h10a2 2 0 002-2V9a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2z"></path>
                    </svg>
                  </div>
                </div>
                <div class="ml-4">
                  <h3 class="text-lg font-medium text-gray-900">Paint Catalog</h3>
                  <p class="text-sm text-gray-500">Browse available paints and colors</p>
                </div>
              </div>
              <div class="mt-4">
                <Link href="/paints" class="text-blue-600 hover:text-blue-800 text-sm font-medium">
                  Browse Paints →
                </Link>
              </div>
            </div>
          </div>

          <!-- Manage Projects -->
          <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg hover:shadow-md transition-shadow">
            <div class="p-6">
              <div class="flex items-center">
                <div class="flex-shrink-0">
                  <div class="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center">
                    <svg class="w-6 h-6 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"></path>
                    </svg>
                  </div>
                </div>
                <div class="ml-4">
                  <h3 class="text-lg font-medium text-gray-900">Projects</h3>
                  <p class="text-sm text-gray-500">Create and manage wall projects</p>
                </div>
              </div>
              <div class="mt-4">
                <Link href="/projects" class="text-green-600 hover:text-green-800 text-sm font-medium">
                  View Projects →
                </Link>
              </div>
            </div>
          </div>

          <!-- Paint Bundles -->
          <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg hover:shadow-md transition-shadow">
            <div class="p-6">
              <div class="flex items-center">
                <div class="flex-shrink-0">
                  <div class="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center">
                    <svg class="w-6 h-6 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"></path>
                    </svg>
                  </div>
                </div>
                <div class="ml-4">
                  <h3 class="text-lg font-medium text-gray-900">Paint Bundles</h3>
                  <p class="text-sm text-gray-500">Manage your paint collections</p>
                </div>
              </div>
              <div class="mt-4">
                <Link href="/paint-bundles" class="text-purple-600 hover:text-purple-800 text-sm font-medium">
                  View Bundles →
                </Link>
              </div>
            </div>
          </div>

          <!-- Admin Panel (for admins only) -->
          <div v-if="isAdmin" class="bg-white overflow-hidden shadow-sm sm:rounded-lg hover:shadow-md transition-shadow">
            <div class="p-6">
              <div class="flex items-center">
                <div class="flex-shrink-0">
                  <div class="w-12 h-12 bg-red-100 rounded-lg flex items-center justify-center">
                    <svg class="w-6 h-6 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"></path>
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
                    </svg>
                  </div>
                </div>
                <div class="ml-4">
                  <h3 class="text-lg font-medium text-gray-900">Admin Panel</h3>
                  <p class="text-sm text-gray-500">Manage users and settings</p>
                </div>
              </div>
              <div class="mt-4 space-x-4">
                <Link href="/admin/users" class="text-red-600 hover:text-red-800 text-sm font-medium">
                  Manage Users →
                </Link>
                <Link href="/admin/user-groups" class="text-red-600 hover:text-red-800 text-sm font-medium">
                  User Groups →
                </Link>
              </div>
            </div>
          </div>
        </div>

        <!-- User Info & Quick Stats -->
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <!-- User Information -->
          <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
            <div class="p-6">
              <h3 class="text-lg font-semibold text-gray-900 mb-4">Your Account</h3>
              <div class="space-y-3">
                <div class="flex justify-between">
                  <span class="text-gray-600">Role:</span>
                  <span class="font-medium">
                    <span v-if="isAdmin" 
                          class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800">
                      Administrator
                    </span>
                    <span v-else 
                          class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800">
                      User
                    </span>
                  </span>
                </div>
                <div v-if="userGroups && userGroups.length > 0" class="flex justify-between">
                  <span class="text-gray-600">Groups:</span>
                  <div class="flex flex-wrap gap-1">
                    <span v-for="group in userGroups" :key="group.id"
                          class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                      {{ group.name }}
                    </span>
                  </div>
                </div>
                <div class="flex justify-between">
                  <span class="text-gray-600">Member since:</span>
                  <span class="font-medium">{{ formatDate(user.created_at) }}</span>
                </div>
              </div>
            </div>
          </div>

          <!-- Quick Stats -->
          <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
            <div class="p-6">
              <h3 class="text-lg font-semibold text-gray-900 mb-4">Quick Stats</h3>
              <div class="space-y-3">
                <div class="flex justify-between">
                  <span class="text-gray-600">Total Paints:</span>
                  <span class="font-medium">{{ stats.paintCount }}</span>
                </div>
                <div class="flex justify-between">
                  <span class="text-gray-600">Your Projects:</span>
                  <span class="font-medium">{{ stats.userProjectCount }}</span>
                </div>
                <div class="flex justify-between">
                  <span class="text-gray-600">Total Users:</span>
                  <span class="font-medium">{{ stats.userCount }}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </AppLayout>
</template>

<script setup>
import { computed } from 'vue'
import { Link, usePage } from '@inertiajs/vue3'
import AppLayout from '../Layouts/AppLayout.vue'

// Props from Laravel controller
const props = defineProps({
  auth: Object,
  stats: Object,
})

const page = usePage()

// Safely access auth data with computed properties
const auth = computed(() => props.auth || page.props.auth || {})
const user = computed(() => auth.value.user || {})
const userName = computed(() => user.value.name || '')
const isAdmin = computed(() => user.value.role === 'admin')
const userGroups = computed(() => user.value.user_groups || [])

// Methods
const formatDate = (dateString) => {
  if (!dateString) return 'Unknown'
  const date = new Date(dateString)
  return date.toLocaleDateString('en-US', { year: 'numeric', month: 'short' })
}
</script>
